---

#
# Install containerd container rumtime
#
- name: Extract containerd tarball
  unarchive:
    src: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/containerd-{{ containerd_version }}-{{ node_os }}-{{ node_arch }}.tar.gz"
    dest: /usr/local/
    remote_src: yes

- name: Create containerd config folder
  file:
    state: directory
    path: /etc/containerd

- name: Get the systemd service file
  get_url:
    url: "https://raw.githubusercontent.com/containerd/containerd/v{{ containerd_version }}/containerd.service"
    dest: /usr/lib/systemd/system/containerd.service

- name: Enable containerd service
  systemd:
    name: containerd.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Extract crictl tarball
  unarchive:
    src: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-{{ node_os }}-{{ node_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes

- name: crictl.yaml
  copy:
    dest: /etc/crictl.yaml
    content: |
      # see: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
      timeout: 2
      debug: true
      pull-image-on-create: false