---
- name: Install prerequisite packages
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: True
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg

- name: Create /etc/apt/keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Kubernetes GPG key
  get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key"
    dest: /tmp/kubernetes-release.key

- name: Dearmor Kubernetes GPG key
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /"
    state: present
    filename: kubernetes

- name: Install kubeadm, kubelet, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: True

- name: Hold kubeadm, kubelet, kubectl at current version
  dpkg_selections:
    name: '{{ item }}'
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Send over kubelet extra args addition
  copy:
    dest: /etc/default/kubelet
    content: |-
      KUBELET_EXTRA_ARGS="--image-credential-provider-bin-dir=/usr/local/bin --image-credential-provider-config=/credential-provider-config.yaml"
  when: docker_hub_user | length > 0 and docker_hub_token | length > 0

- name: Send over credential provider
  copy:
    dest: /usr/local/bin/docker-credential-provider
    mode: 0755
    content: |-
      #!/bin/bash

      cat <<EOF
      {
        "kind": "CredentialProviderResponse",
        "apiVersion": "credentialprovider.kubelet.k8s.io/v1",
        "cacheKeyType": "Registry",
        "auth": {
          "https://index.docker.io/v1/": {
            "username": "{{ docker_hub_user }}",
            "password": "{{ docker_hub_token }}"
          }
        }
      }
      EOF
  when: docker_hub_user | length > 0 and docker_hub_token | length > 0

- name: Send over credential provider config
  copy:
    dest: /credential-provider-config.yaml
    content: |-
      apiVersion: kubelet.config.k8s.io/v1
      kind: CredentialProviderConfig
      providers:
      - name: "docker-credential-provider"
        apiVersion: credentialprovider.kubelet.k8s.io/v1
        matchImages:
        - "*.docker.io"            # Match any images from docker.io
        - "docker.io"              # Explicitly match docker.io
        - "index.docker.io"        # Match index.docker.io
        defaultCacheDuration: "1h" # Cache credentials for 1 hour
  when: docker_hub_user | length > 0 and docker_hub_token | length > 0

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start kubelet service
  systemd:
    name: kubelet
    state: started
    enabled: yes
