---
- name: System prep for Kubernetes
  include_tasks: 00_sysprep.yaml

- name: Setup runc
  include_tasks: 01_runc.yaml

- name: Setup containerd
  include_tasks: 02_containerd.yaml

- name: Setup CNI plugins
  include_tasks: 03_cni_plugins.yaml

- name: Install kubeadm, kubelet, kubectl binaries
  include_tasks: 04_kubernetes.yaml

- name: Install Cilium CLI
  include_tasks: 05_cilium.yaml

- name: Install etcd tools
  include_tasks: 06_etcd_tools.yaml

- name: Install Helm
  include_tasks: 08_helm.yaml

- name: Install Tailscale
  include_tasks: 07_tailscale.yaml
  when: tailscale_enabled | default(false)
