---
apiVersion: kubeadm.k8s.io/v1beta4
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "{{ bootstrap_tailscale_ip }}:6443"
    token: "{{ join_token }}"
    caCertHashes:
      - "{{ join_ca_hash }}"
nodeRegistration:
  kubeletExtraArgs:
    - name: node-ip
      value: "{{ tailscale_ip }}"
